### PR TITLE
various Improvements

### PR DESCRIPTION
**Pull request by tripodsan**
sorry for somewhat large PR, but I tried to keep the various changes in individual commits.

### what I did:
- added the configuration options to the README
- move the example usage to a `example` directory
- create proper mocha unit tests that build and test the output
- set proper directories during compilation to allow correct template resolution
- added option to exclude runtime during compilation
- added option to specify runtime variable names
- added option to specify module import generator

### CODE REVIEW

**Comment by backflip** [comment]
Awesome, thanks a lot!

A few notes:
- I would prefer to ditch `fs-extra` and use `fs.mkdir` and `rimraf` instead. This would slightly reduce the dev dependency footprint and we could easily replace `rimraf` with recursive `fs.rmdir` at some point (available in [Node 10.12+](https://nodejs.org/tr/blog/uncategorized/10-lts-to-12-lts/#notable-changes-in-node-js-12-10-0)).
- It would be great if the options in the README would link to the corresponding test.

Would you be willing to change this or should we rather merge and I update it myself? I'm planning on adding ESLint after merging this anyway, since we are starting to have enough code to warrant this, so it would be fine to take care of these minor changes as well.

**Review by backflip — APPROVED** [review]

**Comment by tripodsan** [comment]
@backflip I think that fs-extras is superior as it it just a think wrapper around fs and adds proper promise support.. you could also use fs.promise instead. I don't mind requiring node 10.12+ for the tests.

please go ahead and adjust the code as you whish...thanks for all your work!

**Comment by backflip** [comment]
Currently on my phone, but I’ll publish it on npm in the evening.

**Comment by backflip** [comment]
Published as [v2.0.0](https://github.com/backflip/htl-loader/releases/tag/v2.0.0)

**Pull request merged**
